### PR TITLE
Documentation Cleanup

### PR DESCRIPTION
**Pull request by Soggi**
Removed the old and inaccurate comment found in most files about how to fill out the `Table of New Infection Parts`, and added a corrected guide into the WRITING_GUIDE.md file for reference.
Replaced comments in files about `Cunt Tightness` (a bunch incorrectly said it should go from 1-5, and it wasn't clear it was inches circumference)

### CODE REVIEW

**Comment by Soggi** [comment]
Sorry for the messy commit messages, I couldn't figure out how to squash them without messing up the merge.

One thing that made it really hard for me to get started was a bunch of old code references in comments that made it hard to Ctrl+F around to find good examples of other work, I think this will help new people a lot.

**Comment by Wahn128** [comment]
Reject this pull request, as it removes all of the prepared NEW infection code, ready to be filled out.

**Review by Wahn128 — CHANGES_REQUESTED** [review]
Reject this, as it kills prepped code segments in hundreds of files.

**Comment by Nuku** [comment]
Prepped code segments?

**Pull request closed without merging**
