### PR TITLE
Possible Dragator fix

### PR DESCRIPTION
**Pull request by BlueBishop**
Maybe this is the issue?

### CODE REVIEW

**Comment by Nuku** [comment]
I can't see how that would fix it?

**Comment by BlueBishop** [comment]
Graphics display for combat calls type entry for some reason. Dragator is blank, so I filled it in the hopes that a blank entry might be what is freaking it out.

I can't properly test it on my end.

**Comment by Nuku** [comment]
Curious, but why not?

**Comment by BlueBishop** [comment]
My build isn't one that handles graphics, so I can't test anything graphic-related.

I had to uncover the bug by downloading a build from the blog site.

**Comment by Nuku** [comment]
Why not update to the most recent build?

**Comment by TigerStripes** [comment]
Local testing using Inform doesn't display the graphics.  Never has for
me.  Don't know why.  It just doesn't.

**Comment by Nuku** [comment]
You can use the same parser that you download with the installer to run the
test.

**Pull request merged**
