### PR TITLE
Susan updated

### PR DESCRIPTION
**Pull request by Richard-Defth**

### CODE REVIEW

**Comment by Richard-Defth** [comment]
why does it send all of them?

**Comment by Richard-Defth** [comment]
can you compile only the susan update? or i need to make a pull with only that one?

**Comment by Nuku** [comment]
It appears that you capitalized susan everywhere, so each of those is a difference.

**Comment by Nuku** [comment]
Compiling.

**Comment by Nuku** [comment]
Do look at the fix I did to get it to compile.

**Pull request merged**
