### PR TITLE
liquidshifter.i7x

### PR DESCRIPTION
**Pull request by Ssely**
Fun to do this but don't know who to contact, where to put the god damn file and if I got the code right! x)
Hoping this is right but direct me on what I've done wrong!

### CODE REVIEW

**Comment by Nuku** [comment]
It should be in a folder of the author name you set, fixed that, compiling...

**Comment by Nuku** [comment]
You appear to have used spaces instead of tabs in the code, fixing...

**Comment by Nuku** [comment]
You can't have quotes inside quotes, replacing with [']

**Comment by Ssely** [comment]
Yeah, excuse me! I'm not really that good with code.

**Comment by Nuku** [comment]
Do take a look at the fixed up file.

**Comment by Nuku** [comment]
https://github.com/Nuku/Flexible-Survival/commit/63455d6639f44fe535b73c11f484e91cf0de70ea#diff-aac4667fa718ca13a03e106cbe1e10e9

**Comment by Nuku** [comment]
https://github.com/Nuku/Flexible-Survival/commit/07877226e1773f57c01c16bf8459a5eec77a5a4f#diff-aac4667fa718ca13a03e106cbe1e10e9 -- These are my fixes.

**Pull request merged**
