### PR TITLE
inv speedup attempt

### PR DESCRIPTION
**Pull request by XinacS**
currently as a separate "scxinv" command this is an attempt to improve the existing inventory system.

### CODE REVIEW

**Comment by Nuku** [comment]
Is this activated? I see no change in the primary story file.

**Comment by XinacS** [comment]
no, I didn't dare to include it in the story file, should I?

**Comment by XinacS** [comment]
at the moment it just replaces "inv" with another version "scxinv", so the original would still be intact, so maybe I could include it without much problems. just a sec.

**Comment by XinacS** [comment]
it's in. :)

**Comment by Nuku** [comment]
Nothing ventured, nothing gained, as they say.

**Comment by XinacS** [comment]
so, you can compare those two. with a full bag of things it should make a noticeable difference.

**Pull request merged**
