### PR TITLE
update liquidshifter.i7x less gunk more fun

### PR DESCRIPTION
**Pull request by Ssely**

### CODE REVIEW

**Comment by Nuku** [comment]
Sidenote, this one was done perfectly, in terms of the patch request and everything.

**Comment by Ssely** [comment]
Cool, thank you! Is there any info/documentation on making NPCs/Other content? For now this is simple enough for a writer, but I'd love to make an NPC of some sort.

**Comment by Wahn128** [comment]
How about you join us on the Discord channel and we can talk about things...

**Comment by Wahn128** [comment]
We should talk, so please join the discord channel (https://discord.gg/gZG2nw6) and poke me there. 

There are a number of errors in your creature. For example, all of the body shape and changing messages - which do not follow the guidance instructions in the comments...

**Comment by Ssely** [comment]
My mistake. I think I've fixed it. I'll be on Discord tomorrow night - timezones and all. Thanks for letting me know.

**Pull request merged**
