### PR TITLE
Hermaid defeat scene for males with More Anal

### PR DESCRIPTION
**Pull request by 10tothe18attoparsecs**
Along with some quick formatting to code to hopefully prevent any errors.

### CODE REVIEW

**Comment by 10tothe18attoparsecs** [comment]
Pretty sure this merge request was done incorrectly, sorry about that.

**Comment by Nuku** [comment]
Fixing little things that make it not compile...

**Comment by Nuku** [comment]
Committed and pushed. Let's announce it to the world!

**Comment by Nuku** [comment]
Oh, what I had to do to fix it: https://github.com/Nuku/Flexible-Survival/commit/1af56ecdb22ac41844c701744940a5114f5d0398

**Comment by 10tothe18attoparsecs** [comment]
What were the issues? Just so that I can make sure they work next time.

**Comment by 10tothe18attoparsecs** [comment]
Oh woops didn't see

**Comment by Nuku** [comment]
-	if anallevel is less than 3 or a random chance at 1 in 2 succeeds :
+	if anallevel is less than 3 or a random chance of 1 in 2 succeeds:

'of' not 'at' in this case.

The other was the quoted line was too long, so I cut it off and put the wait in its own say, then continued.

**Comment by 10tothe18attoparsecs** [comment]
Glad that it only had those, thanks!

**Pull request merged**
