### PR TITLE
lap ride

### PR DESCRIPTION
**Pull request by TigerStripes**

### CODE REVIEW

**Comment by TigerStripes** [comment]
Nuku, I see you're struggling to get it running on the new build.  As a
heads up, all the updates you've done do compile on the old version of
Inform.  Also, was it bringing up errors for the stuff of Zero's?  Those
files should not even be included.

**Comment by Nuku** [comment]
Wait, what I have compiles with the old one?

**Comment by TigerStripes** [comment]
Have you been trying to add back in the old files?  I can't tell because
you've made no change to the story.ni file that I can see.

**Comment by Nuku** [comment]
No? Odd, moment.

**Comment by TigerStripes** [comment]
Okay, it compiles in the old version if I don't add back in the removed
files but do include the other corrections.  Will continue testing...

**Comment by Nuku** [comment]
My Bug report: http://inform7.com/mantis/view.php?id=1816

**Comment by TigerStripes** [comment]
Trying to re-add even one of the files overloads the old version of
Inform.  Time to download the new version and see what results I can get.

**Comment by TigerStripes** [comment]
- New version of Inform fails to compile even with none of the removed
files put back in, getting the same error your received.  This did not
occur until the very end of the compiling process.



*Translating the Source - Failed*

The application ran your source text through the Inform 7 compiler, as
usual, but the compiler unexpectedly failed. This should not happen even if
your source text is gibberish, so you may have uncovered a bug in the
program.

When a program like the I7 compiler fails, it typically returns an error
number: this time, the number was 2, so I7 probably stopped because of a
fatal file-system error.

It is very unlikely that your computer is at fault. More likely causes are:


   - disc space running out on the volume holding the project;
   - trying to run a project from a read-only volume, such as a burned CD
   or DVD;
   - trying to run a project which belongs to another user, whose files you
   have no permission to alter.

However, if you think it more likely that the Inform 7 compiler is at
fault, please check that you have the currently distributed build of the
system: if you have, please consider taking the time to fill out a bug
report at the Inform bug tracker (www.inform7.com/bugs).

*Sorry for the inconvenience.*

**Comment by Nuku** [comment]
A new way for Inform to be unhappy with large files, yay!

**Comment by TigerStripes** [comment]
Well, I must get to bed.  Just a heads up, when it comes to trying to put
the files back in, there's a few things to be aware of:
- Zero's stuff is to remain out.  It was cut long ago due to extensive
problems.
- Some of the extensions have been edited/tweaked to accommodate the fact
that some other files were removed.
- Some extensions are essentially closed by having most of their content
commented out instead of closing the files entirely as small parts needed
to be left to keep other material from coming up with errors.
- You should focus on getting it running w/o the removed content put back
in first and then I can work to re-add the other stuff, as I've got a
better idea of what I removed and why.  For this, I'll send an updated
story.ni file, which is essentially your edits and fixes (and a few other
tweaks), but without the extension re-integration.
- If you do want to test adding material back in once this error is
resolved, start by adding stuff like: Rodeo Clown, Squid, Math Teacher and
Quilled Tousky.  They're all pretty much self-contained and
well-functioning files.

**Pull request merged**
