### PR TITLE
Bunny Heat and Corrections

### PR DESCRIPTION
**Pull request by TigerStripes**

### CODE REVIEW

**Comment by Nuku** [comment]
*Problem.* An internal error has occurred: # in registration of subset
meaning. The current sentence is 'a library computer is a desktop computer'
  <source:C:\Users\David\Documents\Inform\Extensions\hellerhound\power
plant.i7x#line189>; the error was detected at line 462 of "inform7/Chapter
10/Excerpt Meanings.w". This should never happen, and I am now halting in
abject failure.

What has happened here is that one of the checks Inform carries out
internally, to see if it is working properly, has failed. There must be a
bug in this copy of Inform. It may be worth checking whether you have the
current, up-to-date version. If so, please report this problem via
www.inform7.com/bugs.

 As for fixing your source text to avoid this bug, the last thing you
changed is probably the cause, if there is a simple cause. Your source text
might in fact be wrong, and the problem might be occurring because Inform
has failed to find a good way to say so. But even if your source text looks
correct, there are probably rephrasings which would achieve the same effect.


What happen?

**Comment by TigerStripes** [comment]
Fuck.  I've got to go to work.  I'll have to look into it after I get home.

**Comment by TigerStripes** [comment]
I did no changes involving this file or to the 'Computers.i7x' file it calls to include.  I also just downloaded the most recent updates made to the game and tried compiling again.  I do not receive this error.  Did you download a newer version of Inform?  Can you try again?  This seems to be an issue on your end.

**Comment by Nuku** [comment]
6L38 version of Inform. Just redownloaded, same error.

**Comment by TigerStripes** [comment]
I really don't know what to say.  I've not got the same issue locally.  I just copied over everything from my directory, finding some typo fixes and other minor additions I'd missed sending.  I can't really see them making the difference, but I'm sending them anyhow.

**Comment by TigerStripes** [comment]
What fixed it?

**Comment by Nuku** [comment]
It compiled after pulling your latest. It could have been a file length
thing?

**Comment by TigerStripes** [comment]
I guess.  I don't think there was anything new of note in there.  I'm just
glad it's working now.

**Pull request merged**
