### PR TITLE
Fun w/Good Alexandra

### PR DESCRIPTION
**Pull request by TigerStripes**
Let's see if an update to something completely different compiles.

### CODE REVIEW

**Comment by TigerStripes** [comment]
Any problems merging this one?

**Comment by XinacS** [comment]
FYI:
"The source of the problem does not really seem to be an error in a script file. The compiler itself seems to be running into a limit, but one that he does not manage to display properly like MAX_SYMBOLS or the ones.
If you disable the include for any big file or comment out some larger code portion (e.g. not include "Panther Herm by Sarokcat" (Sorry, Sarokcat! This is purely random. I have nothing against you or the Panther Herm. ^^)) the game compiles again.
I have played around with all known (to me) compiler limit settings, but did not manage to overcome this. The game might compile on some systems and might crash on others, because the compiler itself is a native application that is different on every system and seems to also run with different default limits."
Maybe you know of some flag to play with that I don't know of.

**Comment by Nuku** [comment]
Good find, but I know not what it is.

**Comment by TigerStripes** [comment]
Well, isn't that just ass.

**Comment by Nuku** [comment]
I've passed this info right along to the devs of Inform, by the way.
http://inform7.com/mantis/view.php?id=1610

**Comment by TigerStripes** [comment]
*fingers crossed*

Given how it's coming up when a new critter is added to the game, perhaps
the limit has to do with that and table size limits?

**Pull request merged**
