### PR TITLE
New Pics, Lots of Small Fixes

### PR DESCRIPTION
**Pull request by Wahn128**
There'll be another pull request in the next 3 days with further new content. No need to compile this one yet...

### CODE REVIEW

**Comment by Nuku** [comment]
Can you implement the last two pictures I shoved in?

**Comment by Wahn128** [comment]
Ah, these came just in? I can add them to be displayed at the proper spots, most likely tomorrow...

**Comment by Nuku** [comment]
Please and many thanks, good sir.

**Comment by Wahn128** [comment]
There, that should be it. Please do merge all the combined updates.

**Comment by Nuku** [comment]
Compiling!

**Pull request merged**
