### PR TITLE
Request for Lance + Various Fixes/Stuff

### PR DESCRIPTION
**Pull request by TigerStripes**

### CODE REVIEW

**Comment by Nuku** [comment]
Cryptic error returns!

**Comment by TigerStripes** [comment]
I didn't compile?

**Comment by Nuku** [comment]
​Correct.

**Comment by TigerStripes** [comment]
Okay.  I'm going to try some testing here by padding out a file with extra
junk so I induce the error locally.

**Comment by TigerStripes** [comment]
How'd you get it to merge?

**Comment by Nuku** [comment]
I added some white space. Hit enter a few times near the top... compiled.
I'm not questioning it.

**Comment by TigerStripes** [comment]
Strange, but I'll take it.  I'm going to try compressing down the Story
Skipper file.  There's a lot of duplication of work in that one.

**Pull request merged**
